version: '3.9'
services:
  webclient:
    build: ./webclient/
    volumes:
      - ./webclient:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - net1
  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/realm-config/realm-export.json
      PROXY_ADDRESS_FORWARDING: true
    volumes:
      - ./keycloak:/opt/jboss/keycloak/realm-config
    ports:
      - 8080:8080
    networks:
      - net1
  server:
    build: ./server/
    volumes:
      - ./server:/usr/src/server
    working_dir: /usr/src/server
    command: sh -c "go build && ./nicomment"
    ports:
      - "8008:8008"
    stdin_open: true
    networks:
      - net1
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - net1
networks:
  net1: